/* Auto-generated from the 30-case Bhudrishti research dataset. */
window.BHUDRISHTI_RISK_DATA = [
  {
    "Case ID": "RISK-001",
    "Location Name": "Chungthang",
    "District": "Mangan (North Sikkim)",
    "Risk Type": "Flood / GLOF",
    "Risk Level": "High",
    "Risk Reason": "Chungthang lies in the Teesta basin and was a major impact area during the 4 Oct 2023 South Lhonak GLOF. SSDMA's post-disaster assessment also places the Chungthang region in medium-high to very-high multi-hazard zones.",
    "Warning Signs": "Rapid rise in river level; intense/prolonged rainfall; official flood/GLOF warnings; unusual debris-laden river flow.",
    "Safety Precautions": "Move away from river banks and low-lying areas; follow official alerts; do not cross flood water; evacuate to higher/safe ground if instructed.",
    "Approx. When Risk May Reduce": "No fixed safe time. Immediate risk reduces only after river levels/rainfall subside and authorities issue an all-clear; underlying flood/GLOF risk remains.",
    "Alternative Safe Location/Route": "Use officially opened higher-ground shelters/routes; avoid Teesta river-bank roads and damaged bridges until cleared.",
    "Official Source Page": "https://ssdma.nic.in/resources.html",
    "Official Document / Section to Check": "PDNA → SIKKIM PDNA (2023 GLOF); check Roads & Transport / Chungthang impact section",
    "Verification Note": "Official Government of Sikkim SSDMA source. Open Resources page and click PDNA.",
    "Risk Score": 83
  },
  {
    "Case ID": "RISK-002",
    "Location Name": "Mangan Town",
    "District": "Mangan (North Sikkim)",
    "Risk Type": "Landslide",
    "Risk Level": "High",
    "Risk Reason": "SSDMA states that recurring landslide issues affect the SNT site in Mangan town and has initiated a pilot mitigation project with NDMA support. The work includes slope stabilization and drainage measures, showing that the area requires active landslide-risk management.",
    "Warning Signs": "Continuous heavy rain; fresh cracks; falling stones/debris; blocked drains/jhoras; unusual slope movement or muddy runoff.",
    "Safety Precautions": "Follow weather advisories; move away from slide paths and steep slopes; avoid blocked/affected roads; use only routes cleared by local authorities.",
    "Approx. When Risk May Reduce": "Short-term danger may fall after heavy rain stops and slope/road inspection is completed, but recurring monsoon landslide risk remains.",
    "Alternative Safe Location/Route": "Use authority-approved diversion/open road; move toward stable open areas away from active slide paths.",
    "Official Source Page": "https://ssdma.nic.in/activities.html",
    "Official Document / Section to Check": "Pilot Project for Landslide Mitigation at Mangan (SNT Site)",
    "Verification Note": "Official SSDMA activity page directly states recurring landslide issues at Mangan SNT site.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-003",
    "Location Name": "7th Mile, Gangtok–Tsomgo Road",
    "District": "Gangtok / East Sikkim",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA's landslide inventory identifies the 7th Mile Gangtok–Tsomgo Road slide as an old perennial slide. Documented triggers include steep slope, sheared rocks and water, with road damage noted.",
    "Warning Signs": "Rock/debris fall; cracks or fresh material on road; heavy rain; water seepage; traffic/road closure notices.",
    "Safety Precautions": "Avoid stopping below unstable slopes; follow road-closure instructions; do not cross fresh debris; stay alert during heavy rain and use only cleared routes.",
    "Approx. When Risk May Reduce": "Event risk may reduce after rainfall eases and debris/slope is inspected and cleared; the site remains a perennial landslide location.",
    "Alternative Safe Location/Route": "Use an officially announced diversion or postpone travel if the J.N. Road/Tsomgo route is closed.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → '7th Mile Gangtok–Tsomgo Road' (slide no. 30)",
    "Verification Note": "Official SSDMA publication; listed as a perennial landslide site with road-related impacts.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-004",
    "Location Name": "Jitlang Slide, Rangpo",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA's landslide inventory describes Jitlang Slide at Rangpo as an old, complex and perennial slide. The site has faulted/sheared rock and steep-slope conditions, with recorded damage to NH 31A and habitation.",
    "Warning Signs": "Fresh cracks or slope movement; falling rock/debris; blocked drainage; heavy rain; official road/landslide warning.",
    "Safety Precautions": "Keep away from the slide path and unstable slopes; follow official road closures; do not cross fresh debris; move to a stable open/safe area if authorities advise evacuation.",
    "Approx. When Risk May Reduce": "Immediate danger may reduce after rainfall stops, drainage/slope conditions stabilize and authorities inspect/clear the road. The underlying site remains a perennial landslide hazard.",
    "Alternative Safe Location/Route": "Use only an authority-approved diversion/open route around Rangpo; avoid the affected NH corridor until clearance.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → 'Jitlang Slide, Rangpo' (slide no. 21)",
    "Verification Note": "Official SSDMA publication; exact slide name is listed in the inventory.",
    "Risk Score": 89
  },
  {
    "Case ID": "RISK-005",
    "Location Name": "Lower Tintek Marchak (Dikchu–Singtam corridor)",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records this site as an old perennial debris-avalanche slide. Weak geology, excessive rainfall and unmanaged drainage are listed triggers; past damage included road, houses and agricultural land.",
    "Warning Signs": "Intense/prolonged rain; muddy runoff; falling boulders/debris; new cracks; drain overflow; road blockage.",
    "Safety Precautions": "Avoid the affected slope and road section; follow local traffic restrictions; move away from drainage channels and slide paths; use only routes declared open by authorities.",
    "Approx. When Risk May Reduce": "Short-term risk may reduce after heavy rainfall ends, drainage flow normalizes and the slope/road is inspected. Recurrence remains possible because the site is classified as perennial.",
    "Alternative Safe Location/Route": "Use an officially announced Dikchu–Singtam diversion when available; otherwise delay travel until the road is cleared.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → 'Lower Tintek Marchak Slide' (slide no. 24)",
    "Verification Note": "Official SSDMA publication; exact slide name is listed in the inventory.",
    "Risk Score": 89
  },
  {
    "Case ID": "RISK-006",
    "Location Name": "2nd Mile, Kumrek",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA's inventory identifies 2nd Mile Kumrek as an old perennial complex slide. Adverse geology, steep slope and toe cutting are listed as triggers, with recorded damage to road and forest.",
    "Warning Signs": "Rock/soil fall; visible slope cracks; road-edge deformation; heavy rainfall; fresh debris on the road.",
    "Safety Precautions": "Do not stop below unstable cut slopes; obey closures; avoid crossing active debris; remain alert during rain and use only cleared road sections.",
    "Approx. When Risk May Reduce": "Event-level danger may reduce after rainfall and slope movement subside and road inspection is completed. Long-term susceptibility remains because the slide is recorded as perennial.",
    "Alternative Safe Location/Route": "Follow authority-approved alternative roads or postpone travel if the affected road section is closed.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → '2nd Mile, Kumrek Slide' (slide no. 23)",
    "Verification Note": "Official SSDMA publication; exact slide name is listed in the inventory.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-007",
    "Location Name": "Chandmari, Gangtok",
    "District": "Gangtok District",
    "Risk Type": "Landslide",
    "Risk Level": "High",
    "Risk Reason": "SSDMA operates a real-time landslide early-warning system at Chandmari. Sensors monitor ground movement and moisture and are used to identify threshold conditions for potential landslides, indicating a location requiring active landslide monitoring.",
    "Warning Signs": "Official early-warning alert; abnormal ground movement; increasing soil moisture after heavy rain; fresh cracks; small rock/soil falls.",
    "Safety Precautions": "Follow official warnings immediately; move away from unstable slopes/slide paths; stay alert during heavy rainfall; evacuate to a designated safe area if instructed.",
    "Approx. When Risk May Reduce": "Short-term danger may reduce when rainfall stops, sensor readings return to stable levels and authorities withdraw the warning. No fixed safe time should be assumed.",
    "Alternative Safe Location/Route": "Move to an officially designated stable/open safe area; use only local routes confirmed open by authorities.",
    "Official Source Page": "https://ssdma.nic.in/activities.html",
    "Official Document / Section to Check": "Real-Time Landslide Early Warning System – Chandmari, Gangtok",
    "Verification Note": "Official SSDMA activity page documents the real-time early-warning system at Chandmari.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-008",
    "Location Name": "South Lhonak Glacial Lake / downstream Teesta corridor",
    "District": "Mangan (North Sikkim)",
    "Risk Type": "Flood / GLOF",
    "Risk Level": "High",
    "Risk Reason": "South Lhonak is a critical glacial lake monitored for GLOF risk. It was associated with the 4 October 2023 GLOF disaster that severely affected downstream Teesta-valley areas, so sudden lake outburst and downstream flood propagation are key hazards.",
    "Warning Signs": "Official GLOF/flood alert; unusual lake or river-level rise; intense precipitation; sudden debris-laden flow; evacuation warnings for downstream areas.",
    "Safety Precautions": "Move to higher ground away from river channels and low-lying flood zones; follow SSDMA/local authority alerts; never attempt to cross fast flood water; evacuate when instructed.",
    "Approx. When Risk May Reduce": "Immediate downstream danger may reduce only after lake/river monitoring stabilizes and authorities issue an all-clear. The long-term GLOF hazard cannot be assigned a fixed end time.",
    "Alternative Safe Location/Route": "Use designated higher-ground shelters/routes and avoid the Teesta river corridor or damaged bridges until authorities confirm safe access.",
    "Official Source Page": "https://ssdma.nic.in/activities.html",
    "Official Document / Section to Check": "GLOF Monitoring → South Lhonak Glacial Lake, North Sikkim",
    "Verification Note": "Official SSDMA activity page lists South Lhonak monitoring; the 2023 event is also documented in the PDNA.",
    "Risk Score": 83
  },
  {
    "Case ID": "RISK-009",
    "Location Name": "13th Mile Slide, J.N. Road",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA's landslide inventory records the 13th Mile slide on J.N. Road as an old active landslide. It is associated with steep slope conditions, downslope-dipping rock foliation, freeze-thaw action and rainwater, with J.N. Road listed as damaged infrastructure.",
    "Warning Signs": "Heavy/prolonged rain; fresh rock or debris fall; cracks/subsidence near the road; unusual slope movement; official road warning or closure.",
    "Safety Precautions": "Avoid stopping below unstable slopes; follow road-closure instructions; do not cross fresh debris; keep away from active slide zones and use only routes cleared by authorities.",
    "Approx. When Risk May Reduce": "Immediate travel risk may reduce after rainfall stops, slope movement stabilizes and authorities inspect/clear the road. The site remains an active recorded landslide location.",
    "Alternative Safe Location/Route": "Use only an officially opened diversion; postpone J.N. Road travel if the affected section is closed.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → '13th Mile Slide on J.N. Road' (slide no. 31)",
    "Verification Note": "Official SSDMA inventory lists the site as active and records J.N. Road damage. 'High' is a Bhudrishti research classification, not a live alert.",
    "Risk Score": 87
  },
  {
    "Case ID": "RISK-010",
    "Location Name": "14th Mile Slide, J.N. Road",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA's inventory identifies the 14th Mile slide on J.N. Road as an old perennial slide. The documented triggers include steep slope, highly jointed/sheared rock and vibration, and the inventory records damage to J.N. Road.",
    "Warning Signs": "Rock/boulder fall; fresh debris; visible cracks; heavy rain; vibration-related slope movement; official traffic restriction.",
    "Safety Precautions": "Stay away from unstable cut slopes; obey road closures; do not cross fresh slide material; travel only after the road section is officially cleared.",
    "Approx. When Risk May Reduce": "Event-level danger may reduce after slope conditions stabilize and inspection/clearance is completed. Long-term susceptibility remains because the slide is recorded as perennial.",
    "Alternative Safe Location/Route": "Use an authority-approved alternate route or delay travel while the affected J.N. Road section is closed.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → '14th Mile Slide on J.N. Road' (slide no. 33)",
    "Verification Note": "Official SSDMA inventory records the slide as perennial with J.N. Road damage. Project risk rating is not a current warning.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-011",
    "Location Name": "Kyongsla Slide, J.N. Road (15th Mile)",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Kyongsla Slide on J.N. Road (15th Mile) as a block-and-wedge failure in jointed gneiss within a shear zone. Steep slope, jointed/sheared rock and vibration are listed triggers, with J.N. Road damage and a return period described as perennial unless corrected.",
    "Warning Signs": "Falling boulders/rock; fresh fractures; debris on road; slope movement; heavy rain or vibration; official closure warning.",
    "Safety Precautions": "Keep clear of the rock-fall zone; do not stop below unstable slopes; obey closures; cross the area only after official inspection and clearance.",
    "Approx. When Risk May Reduce": "Short-term risk may reduce after active movement stops and the road/slope is cleared. The recorded hazard can recur unless corrective stabilization is completed.",
    "Alternative Safe Location/Route": "Follow an officially announced diversion or postpone travel on the affected J.N. Road section.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → 'Kyongsla Slide on JN Road (15th Mile)' (slide no. 36)",
    "Verification Note": "Official SSDMA inventory states 'perennial unless corrected'. 'High' is used for the project dataset, not as a live official alert.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-012",
    "Location Name": "Singtam, Teesta River Corridor",
    "District": "Gangtok District",
    "Risk Type": "Flood / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "Official SSDMA records from the October 2023 Teesta-basin flood document major impacts in Singtam, including a washed-out bridge, extensive NH-10 damage, damaged sewage infrastructure and submergence of power-related facilities. This demonstrates high exposure of low-lying river-corridor infrastructure to severe flood events.",
    "Warning Signs": "Rapid Teesta water-level rise; intense rainfall or upstream flood/GLOF alert; debris-laden water; bridge/road closure; evacuation warning.",
    "Safety Precautions": "Move to higher ground away from the river and low-lying areas; follow official alerts; never cross floodwater; avoid damaged bridges and NH sections until authorities reopen them.",
    "Approx. When Risk May Reduce": "Immediate risk reduces only after river levels fall, rainfall/upstream alerts ease and authorities issue an all-clear. There is no fixed safe-time estimate for a severe flood event.",
    "Alternative Safe Location/Route": "Use designated higher-ground shelters and only routes officially declared open; avoid the Teesta riverbank/NH-10 affected stretch during an active alert.",
    "Official Source Page": "https://ssdma.nic.in/notifications.html",
    "Official Document / Section to Check": "Sikkim GLOF Post Disaster Needs Assessment (PDNA) 2023 → search 'Singtam'; also SSDMA flood damage report dated 19 Oct 2023",
    "Verification Note": "Official Government of Sikkim SSDMA records document 2023 flood damage in Singtam. Dataset rating is historical-risk classification, not a current alert.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-013",
    "Location Name": "Rangpo, Teesta River Corridor",
    "District": "Pakyong District",
    "Risk Type": "Flood / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA's official October 2023 flood-damage record states that Rangpo and nearby areas were severely affected, with NH-10 damage, submerged facilities and riverside habitations, plus extensive infrastructure damage. This indicates significant flood and transport exposure along the Teesta corridor.",
    "Warning Signs": "Rapid river rise; official flood/GLOF warning; intense rainfall; water/debris entering riverside areas; NH-10 closure or bridge/utility disruption.",
    "Safety Precautions": "Move away from riverbanks and low-lying areas; follow evacuation directions; never drive through floodwater; avoid NH-10 and damaged infrastructure until officially cleared.",
    "Approx. When Risk May Reduce": "Immediate danger may reduce after Teesta levels fall and authorities confirm that roads, bridges and utilities are safe. Long-term flood exposure remains and has no fixed end time.",
    "Alternative Safe Location/Route": "Use higher-ground safe areas and authority-approved alternate routes; avoid the Teesta/NH-10 corridor during an active warning.",
    "Official Source Page": "https://ssdma.nic.in/notifications.html",
    "Official Document / Section to Check": "Sikkim GLOF Post Disaster Needs Assessment (PDNA) 2023 → search 'Rangpo'; also SSDMA flood damage report dated 19 Oct 2023",
    "Verification Note": "Official SSDMA records document severe 2023 flood impacts in Rangpo. 'High' is a Bhudrishti research classification, not a live alert.",
    "Risk Score": 89
  },
  {
    "Case ID": "RISK-014",
    "Location Name": "Bordang Slide on Rangpo–Singtam Road",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Bordang as an old, active complex landslide on the Rangpo–Singtam road. The site has sheared Daling-formation rock fragments and a steep slope; NH 31A is listed as damaged. The inventory identifies adverse geology and steep slope as the main triggers.",
    "Warning Signs": "Fresh rock/soil fall; cracks or deformation on the road edge; unusual slope movement; debris after rain; official road restriction or closure.",
    "Safety Precautions": "Keep away from the active slope and fresh debris; obey road closures; do not stop below unstable cut slopes; use only road sections that authorities have inspected and reopened.",
    "Approx. When Risk May Reduce": "Short-term travel risk may reduce after active movement stops and the road/slope is inspected and cleared. Because SSDMA lists the slide as active, susceptibility should not be treated as permanently removed.",
    "Alternative Safe Location/Route": "No specific alternate route is verified in the source; use only an authority-approved diversion/open route.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Bordang Slide on Rangpo–Singtam Road' (East Sikkim slide no. 3)",
    "Verification Note": "Official SSDMA inventory: active slide; NH 31A damage; triggers include adverse geology and steep slope. High = Bhudrishti research classification, not a live alert.",
    "Risk Score": 87
  },
  {
    "Case ID": "RISK-015",
    "Location Name": "Gantey, West Pendam (Singtam–Pendam Road)",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA describes Gantey, West Pendam as a large subsidence/rotational slide with thick slope material and excessive groundwater. Recorded impacts include road, agricultural land, forest and habitation, indicating both transport and settlement exposure.",
    "Warning Signs": "Ground cracks or sinking; tilted/uneven road surface; seepage or unusually wet ground; boulder/soil movement; worsening conditions after prolonged rain.",
    "Safety Precautions": "Move away from visibly subsiding ground and unstable slopes; avoid affected road sections; follow evacuation/traffic instructions; keep drainage paths clear where safe to do so.",
    "Approx. When Risk May Reduce": "There is no reliable fixed recovery time. SSDMA notes no return estimate considering the size of the subsidence; immediate risk should be considered reduced only after ground movement and water conditions stabilize and authorities inspect the site.",
    "Alternative Safe Location/Route": "No official alternate route is specified in the inventory; follow local authority diversions.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Gantey, West Pendam along-Singtam-Pendam Road' (East Sikkim slide no. 5)",
    "Verification Note": "Official SSDMA inventory records road, agriculture, forest and habitation damage; excessive groundwater/thick slope material are noted. High = project classification.",
    "Risk Score": 84
  },
  {
    "Case ID": "RISK-016",
    "Location Name": "Padamchen Slide",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA identifies Padamchen as an old perennial rotational slide involving jointed quartzite, phyllite, rock fragments, soil and large boulders. Recorded damage includes road and agricultural land; triggers include adverse geology, quarrying, steep slope and groundwater.",
    "Warning Signs": "Fresh boulders/rock fragments; widening cracks; seepage; fresh scarps; debris on the road; increased activity after rain or slope cutting.",
    "Safety Precautions": "Avoid the slide path and unstable quarry/slope areas; do not cross fresh debris; obey road closures; travel only after official inspection and clearance.",
    "Approx. When Risk May Reduce": "Immediate risk may reduce after groundwater/rain conditions ease and no new movement is observed, followed by official clearance. SSDMA lists the slide as perennial, so long-term susceptibility remains.",
    "Alternative Safe Location/Route": "No specific safe route is given in the official inventory; use an authority-approved diversion or delay travel.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Padamchen Slide' (East Sikkim slide no. 12)",
    "Verification Note": "Official SSDMA inventory: perennial; road/agricultural damage; triggers include adverse geology, quarrying, steep slope and groundwater. High = project classification.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-017",
    "Location Name": "Namcheybong Slide",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Namcheybong as an old perennial complex/translational slide. Bedrock dips downslope and the site has strong surface/sub-surface water activity. Damage is recorded to agricultural land, houses, forest and road.",
    "Warning Signs": "New ground or wall cracks; slope bulging; increased seepage; muddy runoff; road deformation; small debris falls that may precede larger movement.",
    "Safety Precautions": "Move away from the slide path and unstable buildings/slopes; avoid affected roads; follow local evacuation instructions; do not enter areas with active cracking or debris movement.",
    "Approx. When Risk May Reduce": "Short-term danger may reduce after groundwater levels and rainfall decrease and the slope is inspected as stable. SSDMA classifies the site as perennial, so risk can recur.",
    "Alternative Safe Location/Route": "Use only routes declared open by authorities; no site-specific alternate route is verified in the source.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Namcheybong Slide' (East Sikkim slide no. 25)",
    "Verification Note": "Official SSDMA inventory: houses, road, agriculture and forest affected; high groundwater/downslope bedrock; perennial. High = project classification.",
    "Risk Score": 89
  },
  {
    "Case ID": "RISK-018",
    "Location Name": "Pegay Slide, Pachey (Pakyong–Linkey Road)",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA identifies the Pegay slide as a perennial wedge-type failure on the Pakyong–Linkey road. Joint failure, underground water, steep slope and adverse geology are listed as triggers, while the road and forest are recorded as damaged.",
    "Warning Signs": "Rock wedges or fragments detaching; fresh debris; seepage; cracks along rock joints; road blockage or deformation, especially after rainfall.",
    "Safety Precautions": "Stay clear of rock-fall zones; do not stop below unstable rock faces; follow closures; cross the section only after official inspection and reopening.",
    "Approx. When Risk May Reduce": "Event-level danger may reduce once water conditions and rock movement stabilize and debris is cleared. Perennial classification means recurrence remains possible.",
    "Alternative Safe Location/Route": "Use an authority-approved diversion; the official inventory does not specify a permanent alternate road.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Pegay Slide, Pachey, Pakyong-Linkey Road' (East Sikkim slide no. 26)",
    "Verification Note": "Official SSDMA inventory: perennial wedge failure; Pakyong–Linkey road damage; underground water/steep slope/adverse geology. High = project classification.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-019",
    "Location Name": "Rangchang Khola Slide, Tumin",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Rock-fall Risk",
    "Risk Level": "Medium",
    "Risk Reason": "SSDMA records Rangchang Khola at Tumin as a recent rock-fall site in quartzite/phyllite terrain. Weak geology, steep slope and rainfall are listed triggers. The inventory records forest impact and specifically notes no impact on habitation.",
    "Warning Signs": "Fresh rock fragments below the slope; isolated boulder fall; new cracks in exposed rock; increased fall activity during or after rain.",
    "Safety Precautions": "Keep away from the base of steep rock faces; avoid stopping in rock-fall paths; follow local warnings and move through affected road/slope areas only if officially cleared.",
    "Approx. When Risk May Reduce": "Short-term risk may reduce after rainfall stops and no further rock fall is observed. Because the inventory describes a recent event rather than a verified permanently stabilized site, caution remains appropriate.",
    "Alternative Safe Location/Route": "No specific alternate route is provided; use local authority guidance if access is restricted.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Rangchang Khola Slide (Tumin)' (East Sikkim slide no. 27)",
    "Verification Note": "Official SSDMA inventory: recent rock fall; weak geology/steep slope/rainfall; forest affected, no habitation impact. Medium = project classification.",
    "Risk Score": 56
  },
  {
    "Case ID": "RISK-020",
    "Location Name": "Tsochen–Pheri Slide",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA documents Tsochen–Pheri as a very large perennial complex slide in sheared/rotated gneissic terrain. The inventory records road cut-off since 1997 along with impacts to agricultural land, habitation and forest; adverse geology and high water regime are listed triggers.",
    "Warning Signs": "Persistent ground movement; road cracking or collapse; large boulder/debris movement; strong seepage; renewed instability during prolonged wet periods.",
    "Safety Precautions": "Avoid the active slide mass and closed road; move away from unstable buildings/slopes; follow evacuation and traffic restrictions; do not attempt to cross a cut-off or freshly failed road.",
    "Approx. When Risk May Reduce": "No fixed recovery time should be assumed. Immediate access risk may fall only after movement/water conditions stabilize and engineering/authority inspection confirms safety; SSDMA lists the site as perennial.",
    "Alternative Safe Location/Route": "Use only officially announced alternate access; do not improvise routes across the slide area.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Tsochen–Pheri Slide' (East Sikkim slide no. 28)",
    "Verification Note": "Official SSDMA inventory: perennial; road cut off since 1997; habitation/agriculture/forest impacts; high water/adverse geology. High = project classification.",
    "Risk Score": 89
  },
  {
    "Case ID": "RISK-021",
    "Location Name": "Zang Busty Subsidence, near Dikchu",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Subsidence Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Zang Busty near Dikchu as a large perennial subsidence area with unstable boulders, debris and steep slopes. Road, agriculture and settlement are listed as affected. The inventory also notes groundwater and concerns around rim treatment near the Dikchu reservoir/dam area.",
    "Warning Signs": "Ground sinking or new depressions; cracks in roads/structures; boulder movement; seepage; retaining-wall distress; sudden changes near steep reservoir-side slopes.",
    "Safety Precautions": "Stay away from visibly subsiding ground and unstable boulders; avoid affected roads/structures; follow local evacuation instructions; do not enter cracked or recently moved ground.",
    "Approx. When Risk May Reduce": "Short-term danger may reduce if ground movement and groundwater conditions stabilize and the area is inspected. SSDMA lists the subsidence as perennial, so long-term recurrence remains possible.",
    "Alternative Safe Location/Route": "No verified site-specific alternate route is given; use official diversion/safe-area instructions.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Zang Busty Subsidence (Near Dikchu)' (East Sikkim slide no. 29)",
    "Verification Note": "Official SSDMA inventory: perennial subsidence; road/agriculture/settlement affected; unstable boulders and groundwater noted. High = project classification.",
    "Risk Score": 89
  },
  {
    "Case ID": "RISK-022",
    "Location Name": "Canteen Dara, Sawa Khola near Rongli Bridge",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA identifies this as an old perennial rotational slide with thick slope-forming material and active groundwater. Recorded damage includes the road between Rongli and Rorathang/Rhenock and forest; adverse geology and high groundwater are listed triggers.",
    "Warning Signs": "Road-edge cracks or settlement; muddy seepage; small rotational slumps; debris or boulders reaching the road; worsening after prolonged rainfall.",
    "Safety Precautions": "Avoid the affected slope and road during active movement; obey closures; do not cross fresh slide debris; travel only after road and slope inspection.",
    "Approx. When Risk May Reduce": "Immediate travel risk may reduce after groundwater/rainfall conditions ease and the road is cleared. Perennial classification means the site remains susceptible.",
    "Alternative Safe Location/Route": "Use an authority-approved Rongli-area diversion if announced; no fixed alternate route is verified in the inventory.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Canteen Dara, Sawa Khola near Rongli Bridge' (East Sikkim slide no. 32)",
    "Verification Note": "Official SSDMA inventory: perennial; road/forest damage; active groundwater and adverse geology. High = project classification.",
    "Risk Score": 92
  },
  {
    "Case ID": "RISK-023",
    "Location Name": "Bhutia Khola, Dalapchand–Regle",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Bhutia Khola, Dalapchand–Regle as an old perennial complex/translational slide in highly disturbed Daling-group rocks. The Rongli–Dalapchand road, forest and cardamom areas are listed as damaged; high groundwater and adverse geology are key triggers.",
    "Warning Signs": "Road cracking; slope deformation; boulder movement; increased seepage; debris accumulation; renewed movement after extended wet weather.",
    "Safety Precautions": "Avoid unstable slopes and affected road sections; obey closures; move away from active debris/boulder paths; use only routes officially reopened.",
    "Approx. When Risk May Reduce": "Event risk may reduce after groundwater and movement stabilize and the road is inspected/cleared. SSDMA lists the slide as perennial, so recurrence remains possible.",
    "Alternative Safe Location/Route": "Use only an official diversion; no permanent alternate route is stated in the source.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Bhutia Khola, Dalapchand, Regle' (East Sikkim slide no. 34)",
    "Verification Note": "Official SSDMA inventory: perennial; Rongli–Dalapchand road/forest/cardamom damage; groundwater/adverse geology. High = project classification.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-024",
    "Location Name": "Doksing on Rhenock–Rongli Road",
    "District": "East Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA describes Doksing as a perennial wedge-type landslide in adverse Daling-group geology. The documented slide extends roughly 2 km and has damaged the Rongli–Rhenock road; steep slope and fractured rock are listed triggers.",
    "Warning Signs": "Rock wedges or fragments falling; fresh fractures; debris on carriageway; road-edge distress; increased activity after rain or vibration.",
    "Safety Precautions": "Do not stop below fractured rock slopes; obey closures; avoid crossing fresh debris; move through only after official inspection and clearance.",
    "Approx. When Risk May Reduce": "Short-term road risk may reduce when active rock movement stops and the road is cleared. SSDMA lists the site as perennial, so recurrence remains possible.",
    "Alternative Safe Location/Route": "Use an authority-approved alternate route or delay travel; no specific permanent alternative is verified in the inventory.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Doksing on Rhenock–Rongli Road' (East Sikkim slide no. 35)",
    "Verification Note": "Official SSDMA inventory: perennial wedge failure; Rongli–Rhenock road damaged; steep slope/fractured rock triggers. High = project classification.",
    "Risk Score": 85
  },
  {
    "Case ID": "RISK-025",
    "Location Name": "Mangshila Slide",
    "District": "North Sikkim (source classification)",
    "Risk Type": "Landslide / Road & Settlement Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Mangshila as an old debris slide in a highly disturbed geological formation. Agricultural land, road and houses are listed as damaged, while bad geology and high groundwater/rainwater are identified as triggers.",
    "Warning Signs": "Muddy debris movement; ground cracks; seepage; road obstruction; slope movement near houses or agricultural terraces, especially during wet periods.",
    "Safety Precautions": "Keep away from active debris paths and unstable slopes; avoid blocked roads; follow evacuation instructions if houses are threatened; use only cleared routes.",
    "Approx. When Risk May Reduce": "Immediate risk may reduce after rain/groundwater conditions ease and no new movement is observed, followed by inspection. The source does not provide a reliable return period.",
    "Alternative Safe Location/Route": "No specific alternative route is verified; follow district/local authority diversions.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Mangshila Slide' (North Sikkim slide no. 3)",
    "Verification Note": "Official SSDMA inventory: road, houses and agriculture damaged; bad geology/high ground or rain water triggers. High = project classification.",
    "Risk Score": 84
  },
  {
    "Case ID": "RISK-026",
    "Location Name": "Salem Slide",
    "District": "North Sikkim (source classification)",
    "Risk Type": "Landslide",
    "Risk Level": "Medium",
    "Risk Reason": "SSDMA records Salem as a recent debris-fall site in high-grade metamorphic/gneissic terrain. Forest damage is documented, with adverse geology, slope and rainfall listed as triggers; no specific return period is provided.",
    "Warning Signs": "Fresh soil/rock fragments; small debris falls; new scars on steep slopes; increased activity during or immediately after heavy rain.",
    "Safety Precautions": "Avoid the base of active slopes; stay out of fresh debris zones; follow weather and local warnings; do not approach a slope while material is falling.",
    "Approx. When Risk May Reduce": "Short-term risk may reduce after rainfall ends and the slope remains stable through inspection/observation. Long-term recurrence is not quantified in the official inventory.",
    "Alternative Safe Location/Route": "No route diversion is specified; use local authority guidance if nearby access is restricted.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Salem Slide' (North Sikkim slide no. 5)",
    "Verification Note": "Official SSDMA inventory: recent debris fall; forest damage; adverse geology/slope/rainfall triggers. Medium = project classification due to recorded forest-only impact in the inventory.",
    "Risk Score": 52
  },
  {
    "Case ID": "RISK-027",
    "Location Name": "Pakel Slide (Twin Slides)",
    "District": "North Sikkim (source classification)",
    "Risk Type": "Landslide",
    "Risk Level": "Medium",
    "Risk Reason": "SSDMA identifies Pakel as recent twin debris-flow slides in high-grade gneiss/schist terrain. Steep slope, rainfall, groundwater activity and adverse geology are listed triggers. The recorded damage in the inventory is to forest.",
    "Warning Signs": "Debris channels becoming active; muddy flow; rock/soil fragments; seepage; fresh slope scars; increased movement after intense rain.",
    "Safety Precautions": "Stay out of debris-flow channels and the base of unstable slopes; avoid crossing flowing debris; follow weather/local warnings and access restrictions.",
    "Approx. When Risk May Reduce": "Immediate risk may reduce after rainfall and groundwater conditions subside and debris movement stops. The official inventory does not assign a return period.",
    "Alternative Safe Location/Route": "No alternate route is specified in the source; use local authority advice if access is affected.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Pakel Slide (Twin Slides)' (North Sikkim slide no. 6)",
    "Verification Note": "Official SSDMA inventory: recent debris flow; forest impact; steep slope/rainfall/groundwater/adverse geology triggers. Medium = project classification.",
    "Risk Score": 52
  },
  {
    "Case ID": "RISK-028",
    "Location Name": "Chawang Slide",
    "District": "North Sikkim (source classification)",
    "Risk Type": "Landslide / Settlement Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Chawang as a recent debris-flow site in Daling-group metamorphic rocks. Forest, settlement and agriculture are listed as damaged. Adverse geology, steep slope, rainwater and scouring by a nala are identified as triggers.",
    "Warning Signs": "Muddy or boulder-rich flow in/near the nala; bank erosion; new cracks; slope failures after rain; debris approaching settlement or fields.",
    "Safety Precautions": "Move away from nala/debris-flow channels and unstable slopes; avoid crossings during heavy rain; follow local evacuation instructions and do not enter fresh debris deposits.",
    "Approx. When Risk May Reduce": "Short-term risk may reduce after rainfall ends, nala flow/scouring decreases and the slope is inspected. The official inventory does not provide a fixed recurrence interval.",
    "Alternative Safe Location/Route": "Move to stable higher ground or a designated safe area if instructed; use only officially cleared access routes.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Chawang Slide' (North Sikkim slide no. 8)",
    "Verification Note": "Official SSDMA inventory: settlement/agriculture/forest damaged; steep slope, rainwater and nala scouring triggers. High = project classification.",
    "Risk Score": 82
  },
  {
    "Case ID": "RISK-029",
    "Location Name": "Meyong Slide",
    "District": "North Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA records Meyong as a recent, active wedge-failure site in highly jointed/fractured gneissic rock with quartzite. The road is listed as affected, and steep slope, excess water and vibration are identified as triggers.",
    "Warning Signs": "Rock wedges or boulders detaching; fresh fractures; debris on road; seepage; increased fall activity after rain or vibration.",
    "Safety Precautions": "Keep away from fractured rock faces and road-side fall zones; obey closures; do not cross fresh debris; wait for official slope/road clearance.",
    "Approx. When Risk May Reduce": "Immediate road risk may reduce after water conditions and rock movement stabilize and the road is cleared. SSDMA labels the site active, so continued susceptibility should be expected.",
    "Alternative Safe Location/Route": "Use only an authority-approved diversion/open road; no permanent alternate route is verified in the inventory.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Meyong Slide' (North Sikkim slide no. 12)",
    "Verification Note": "Official SSDMA inventory: active wedge failure; road affected; steep slope/fractured rock/excess water/vibration triggers. High = project classification.",
    "Risk Score": 87
  },
  {
    "Case ID": "RISK-030",
    "Location Name": "Richu Nala near Tong",
    "District": "North Sikkim (source classification)",
    "Risk Type": "Landslide / Road Risk",
    "Risk Level": "High",
    "Risk Reason": "SSDMA identifies Richu Nala near Tong as a very old but active complex slide consisting of debris/soil with boulders. The road is listed as damaged; highly jointed rocks, overburden and scouring by active water are documented triggers.",
    "Warning Signs": "Nala-bank erosion; fresh debris/boulders; road blockage; new cracks; muddy flow; increased scouring and slope movement during high water.",
    "Safety Precautions": "Avoid the active nala margin and slide path; do not cross fresh debris or fast water; obey road closures and use only sections inspected and reopened by authorities.",
    "Approx. When Risk May Reduce": "Immediate travel risk may reduce after water/scouring activity falls and no new movement occurs, followed by road/slope inspection. SSDMA labels the site active, so recurrence remains possible.",
    "Alternative Safe Location/Route": "No site-specific alternate route is verified; follow authority-approved diversion or delay travel.",
    "Official Source Page": "https://ssdma.nic.in/publications.html",
    "Official Document / Section to Check": "Inventory & GIS Mapping of Landslides → search 'Richu Nala near Tong' (North Sikkim slide no. 13)",
    "Verification Note": "Official SSDMA inventory: active complex slide; road damage; jointed rocks/overburden/active-water scouring triggers. High = project classification.",
    "Risk Score": 87
  }
];

window.BHUDRISHTI_RISK_META = {
  scoreNote: "Research-based prototype score. It is not a live government warning or probability.",
  sourceNote: "Official source pages are included so the research can be independently verified."
};
