import { useEffect, useState } from "react";

import apiClient from "../api/client";

import "./AlertsPage.css";


export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");


  useEffect(() => {
    const loadAlerts = async () => {
      try {
        setLoading(true);
        setError("");

        const response = await apiClient.get("/alerts");

        setAlerts(response.data);
      } catch (err) {
        setError(
          err?.response?.data?.detail ||
            "Failed to load alerts."
        );
      } finally {
        setLoading(false);
      }
    };

    loadAlerts();
  }, []);


  if (loading) {
    return (
      <div className="alerts-state">
        Loading alerts...
      </div>
    );
  }


  if (error) {
    return (
      <div className="alerts-state alerts-error">
        {error}
      </div>
    );
  }


  return (
    <main className="alerts-page">
      <span className="section-kicker">
        EARLY WARNING SYSTEM
      </span>

      <h1>Alerts</h1>

      <p>
        Alert records generated by the BhuDrishti risk engine.
        Controlled or historical test alerts are clearly labeled below.
      </p>

      <section className="alerts-page-list">
        {alerts.length === 0 ? (
          <div className="alerts-empty">
            No alerts found.
          </div>
        ) : (
          alerts.map((alert) => (
            <article
              className="alerts-page-item"
              key={alert.public_id}
            >
              <div>
                <strong>{alert.title}</strong>

                <p>{alert.message}</p>
              </div>

              <div>
                <span>{alert.severity}</span>
                <span>{alert.status}</span>
                <span>
                  {alert.title === "High Geo-Hazard Warning"
                    ? "TEST / CONTROLLED"
                    : "RECORDED ALERT"}
                </span>
              </div>
            </article>
          ))
        )}
      </section>
    </main>
  );
}


