import { useCallback, useEffect, useState } from "react";

import apiClient from "../api/client";

import "./AlertsPage.css";


function formatLabel(value) {
  if (!value) {
    return "—";
  }

  return String(value)
    .replaceAll("_", " ")
    .replace(/\b\w/g, (character) =>
      character.toUpperCase()
    );
}


function formatDate(value) {
  if (!value) {
    return "—";
  }

  return new Date(value).toLocaleString();
}


export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState("");
  const [error, setError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");


  const loadAlerts = useCallback(async () => {
    try {
      setLoading(true);
      setError("");

      const response = await apiClient.get("/alerts", {
        params: {
          limit: 100,
        },
      });

      setAlerts(response.data);
    } catch (err) {
      setError(
        err?.response?.data?.detail ||
          "Failed to load alerts."
      );
    } finally {
      setLoading(false);
    }
  }, []);


  useEffect(() => {
    loadAlerts();
  }, [loadAlerts]);


  const handleAcknowledge = async (alert) => {
    try {
      setActionLoading(alert.public_id);
      setError("");
      setSuccessMessage("");

      await apiClient.post(
        `/alerts/${alert.public_id}/acknowledge`
      );

      setSuccessMessage(
        "Alert acknowledged successfully."
      );

      await loadAlerts();
    } catch (err) {
      setError(
        err?.response?.data?.detail ||
          "Failed to acknowledge alert."
      );
    } finally {
      setActionLoading("");
    }
  };


  const handleResolve = async (alert) => {
    try {
      setActionLoading(alert.public_id);
      setError("");
      setSuccessMessage("");

      await apiClient.post(
        `/alerts/${alert.public_id}/resolve`
      );

      setSuccessMessage(
        "Alert resolved successfully."
      );

      await loadAlerts();
    } catch (err) {
      setError(
        err?.response?.data?.detail ||
          "Failed to resolve alert."
      );
    } finally {
      setActionLoading("");
    }
  };


  if (loading) {
    return (
      <div className="alerts-state">
        Loading alerts...
      </div>
    );
  }


  return (
    <main className="alerts-page">

      <section className="alerts-header">
        <div>
          <span className="section-kicker">
            EARLY WARNING SYSTEM
          </span>

          <h1>
            Alerts
          </h1>

          <p>
            Geo-hazard warnings generated by the
            BhuDrishti risk assessment pipeline.
          </p>
        </div>

        <div className="alerts-count-card">
          <span>
            Alert Records
          </span>

          <strong>
            {alerts.length}
          </strong>
        </div>
      </section>


      {error && (
        <div className="alerts-feedback alerts-feedback-error">
          {error}
        </div>
      )}


      {successMessage && (
        <div className="alerts-feedback alerts-feedback-success">
          {successMessage}
        </div>
      )}


      <section className="alerts-page-list">

        {alerts.length === 0 ? (
          <div className="alerts-empty">
            <h2>
              No alert records found
            </h2>

            <p>
              The system has not generated any geo-hazard
              warning records for the available risk zones.
            </p>
          </div>
        ) : (
          alerts.map((alert) => {

            const isActive =
              alert.status === "active";

            const isAcknowledged =
              alert.status === "acknowledged";

            const isResolved =
              alert.status === "resolved";

            const isProcessing =
              actionLoading === alert.public_id;

            return (
              <article
                className={`alerts-page-item alert-${alert.severity}`}
                key={alert.public_id}
              >

                <div className="alert-main-content">

                  <div className="alert-title-row">

                    <div>
                      <span className="alert-severity-label">
                        {formatLabel(
                          alert.severity
                        )}
                      </span>

                      <strong>
                        {alert.title}
                      </strong>
                    </div>

                    <span
                      className={`alert-status-badge alert-status-${alert.status}`}
                    >
                      {formatLabel(
                        alert.status
                      )}
                    </span>

                  </div>


                  <p className="alert-message">
                    {alert.message}
                  </p>


                  <div className="alert-metadata">

                    <span>
                      Audience:{" "}
                      <strong>
                        {formatLabel(
                          alert.audience
                        )}
                      </strong>
                    </span>

                    <span>
                      Created:{" "}
                      <strong>
                        {formatDate(
                          alert.created_at
                        )}
                      </strong>
                    </span>

                    {alert.acknowledged_at && (
                      <span>
                        Acknowledged:{" "}
                        <strong>
                          {formatDate(
                            alert.acknowledged_at
                          )}
                        </strong>
                      </span>
                    )}

                    {alert.resolved_at && (
                      <span>
                        Resolved:{" "}
                        <strong>
                          {formatDate(
                            alert.resolved_at
                          )}
                        </strong>
                      </span>
                    )}

                  </div>

                </div>


                <div className="alert-actions">

                  {isActive && (
                    <button
                      type="button"
                      className="alert-action-button alert-acknowledge-button"
                      onClick={() =>
                        handleAcknowledge(alert)
                      }
                      disabled={isProcessing}
                    >
                      {isProcessing
                        ? "Processing..."
                        : "Acknowledge"}
                    </button>
                  )}


                  {(isActive ||
                    isAcknowledged) && (
                    <button
                      type="button"
                      className="alert-action-button alert-resolve-button"
                      onClick={() =>
                        handleResolve(alert)
                      }
                      disabled={isProcessing}
                    >
                      {isProcessing
                        ? "Processing..."
                        : "Resolve"}
                    </button>
                  )}


                  {isResolved && (
                    <span className="alert-resolved-label">
                      Alert Resolved
                    </span>
                  )}

                </div>

              </article>
            );
          })
        )}

      </section>

    </main>
  );
}
