import { useEffect, useState } from "react";

import apiClient from "../api/client";

import "./AlertsPage.css";


function formatLabel(value) {
  if (!value) {
    return "—";
  }

  return String(value)
    .replaceAll("_", " ")
    .replace(/\b\w/g, (character) =>
      character.toUpperCase()
    );
}


function formatDate(value) {
  if (!value) {
    return "—";
  }

  return new Date(value).toLocaleString();
}


export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");


  useEffect(() => {
    const loadAlerts = async () => {
      try {
        setLoading(true);
        setError("");

        const response = await apiClient.get("/alerts", {
          params: {
            limit: 100,
          },
        });

        setAlerts(response.data);
      } catch (err) {
        setError(
          err?.response?.data?.detail ||
            "Failed to load alerts."
        );
      } finally {
        setLoading(false);
      }
    };

    loadAlerts();
  }, []);


  if (loading) {
    return (
      <div className="alerts-state">
        Loading alerts...
      </div>
    );
  }


  if (error) {
    return (
      <div className="alerts-state alerts-error">
        {error}
      </div>
    );
  }


  return (
    <main className="alerts-page">
      <span className="section-kicker">
        EARLY WARNING SYSTEM
      </span>

      <h1>Alerts</h1>

      <p>
        Geo-hazard warnings generated by the BhuDrishti
        risk assessment pipeline.
      </p>

      <section className="alerts-page-list">
        {alerts.length === 0 ? (
          <div className="alerts-empty">
            No alert records found.
          </div>
        ) : (
          alerts.map((alert) => (
            <article
              className="alerts-page-item"
              key={alert.public_id}
            >
              <div>
                <strong>{alert.title}</strong>

                <p>{alert.message}</p>

                <small>
                  Created: {formatDate(alert.created_at)}
                </small>
              </div>

              <div>
                <span>
                  {formatLabel(alert.severity)}
                </span>

                <span>
                  {formatLabel(alert.status)}
                </span>

                <span>
                  {formatLabel(alert.audience)}
                </span>
              </div>
            </article>
          ))
        )}
      </section>
    </main>
  );
}