"""Create weather observations table

Revision ID: 14232cee6309
Revises: cc53557f7fd8
Create Date: 2026-08-24 23:08:36.546189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14232cee6309'
down_revision: Union[str, Sequence[str], None] = 'cc53557f7fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_rate_mm_hr', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('atmospheric_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_latitude'), 'weather_observations', ['latitude'], unique=False)
    op.create_index(op.f('ix_weather_observations_longitude'), 'weather_observations', ['longitude'], unique=False)
    op.create_index(op.f('ix_weather_observations_observed_at'), 'weather_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_provider'), 'weather_observations', ['provider'], unique=False)
    op.create_index(op.f('ix_weather_observations_public_id'), 'weather_observations', ['public_id'], unique=True)
    op.create_index(op.f('ix_weather_observations_received_at'), 'weather_observations', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_received_at'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_public_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_provider'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_observed_at'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_longitude'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_latitude'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
