"""Add device event id to sensor readings

Revision ID: 199abb6b0998
Revises: 6fb6ffe94207
Create Date: 2026-08-28 11:30:00.792785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199abb6b0998'
down_revision: Union[str, Sequence[str], None] = '6fb6ffe94207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('device_event_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_sensor_readings_device_event_id'), 'sensor_readings', ['device_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_device_event_id'), table_name='sensor_readings')
    op.drop_column('sensor_readings', 'device_event_id')
    # ### end Alembic commands ###
