"""Create sensors and sensor readings tables

Revision ID: 45df57b42be9
Revises: f59c8c780e04
Create Date: 2026-08-23 20:49:59.273074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45df57b42be9'
down_revision: Union[str, Sequence[str], None] = 'f59c8c780e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('sensor_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sensor_type', sa.Enum('SOIL_MOISTURE', 'RAIN_GAUGE', 'TILT', 'VIBRATION', 'TEMPERATURE', 'HUMIDITY', 'MULTI_SENSOR', name='sensor_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'FAULTY', 'OFFLINE', name='sensor_status'), nullable=False),
    sa.Column('risk_zone_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('installation_depth_cm', sa.Float(), nullable=True),
    sa.Column('firmware_version', sa.String(length=80), nullable=True),
    sa.Column('battery_level_percent', sa.Float(), nullable=True),
    sa.Column('signal_strength_dbm', sa.Float(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_public_id'), 'sensors', ['public_id'], unique=True)
    op.create_index(op.f('ix_sensors_risk_zone_id'), 'sensors', ['risk_zone_id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_code'), 'sensors', ['sensor_code'], unique=True)
    op.create_index(op.f('ix_sensors_sensor_type'), 'sensors', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensors_status'), 'sensors', ['status'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('soil_moisture_percent', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_rate_mm_hr', sa.Float(), nullable=True),
    sa.Column('tilt_degrees', sa.Float(), nullable=True),
    sa.Column('vibration_level', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('battery_level_percent', sa.Float(), nullable=True),
    sa.Column('signal_strength_dbm', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_public_id'), 'sensor_readings', ['public_id'], unique=True)
    op.create_index(op.f('ix_sensor_readings_received_at'), 'sensor_readings', ['received_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_received_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_public_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensors_status'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_sensor_type'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_sensor_code'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_risk_zone_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_public_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
