"""Create satellite observations table

Revision ID: 5998ec026736
Revises: b50c065a2edb
Create Date: 2026-08-25 22:59:10.373922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5998ec026736'
down_revision: Union[str, Sequence[str], None] = 'b50c065a2edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('risk_zone_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('satellite_name', sa.String(length=100), nullable=True),
    sa.Column('scene_id', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('ndwi', sa.Float(), nullable=True),
    sa.Column('soil_moisture_index', sa.Float(), nullable=True),
    sa.Column('surface_temperature_c', sa.Float(), nullable=True),
    sa.Column('data_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_observations_captured_at'), 'satellite_observations', ['captured_at'], unique=False)
    op.create_index(op.f('ix_satellite_observations_id'), 'satellite_observations', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_observations_latitude'), 'satellite_observations', ['latitude'], unique=False)
    op.create_index(op.f('ix_satellite_observations_longitude'), 'satellite_observations', ['longitude'], unique=False)
    op.create_index(op.f('ix_satellite_observations_provider'), 'satellite_observations', ['provider'], unique=False)
    op.create_index(op.f('ix_satellite_observations_public_id'), 'satellite_observations', ['public_id'], unique=True)
    op.create_index(op.f('ix_satellite_observations_risk_zone_id'), 'satellite_observations', ['risk_zone_id'], unique=False)
    op.create_index(op.f('ix_satellite_observations_scene_id'), 'satellite_observations', ['scene_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellite_observations_scene_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_risk_zone_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_public_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_provider'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_longitude'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_latitude'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_captured_at'), table_name='satellite_observations')
    op.drop_table('satellite_observations')
    # ### end Alembic commands ###
