"""Create weather forecasts table

Revision ID: 5fdec5f4e52d
Revises: 14232cee6309
Create Date: 2026-08-24 23:33:45.674779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdec5f4e52d'
down_revision: Union[str, Sequence[str], None] = '14232cee6309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('precipitation_probability_percent', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('atmospheric_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_forecast_for'), 'weather_forecasts', ['forecast_for'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_generated_at'), 'weather_forecasts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_id'), 'weather_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_latitude'), 'weather_forecasts', ['latitude'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_longitude'), 'weather_forecasts', ['longitude'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_provider'), 'weather_forecasts', ['provider'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_public_id'), 'weather_forecasts', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecasts_public_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_provider'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_longitude'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_latitude'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_generated_at'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_for'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
