"""Create risk assessments table

Revision ID: 60ea98256041
Revises: 9e9b704c7a8a
Create Date: 2026-08-25 21:15:58.035292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ea98256041'
down_revision: Union[str, Sequence[str], None] = '9e9b704c7a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('risk_zone_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'CRITICAL', name='risk_severity'), nullable=False),
    sa.Column('risk_probability_percent', sa.Float(), nullable=False),
    sa.Column('confidence_percent', sa.Float(), nullable=True),
    sa.Column('forecast_horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('dominant_factor', sa.String(length=150), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_assessed_at'), 'risk_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_forecast_horizon_minutes'), 'risk_assessments', ['forecast_horizon_minutes'], unique=False)
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_public_id'), 'risk_assessments', ['public_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_risk_zone_id'), 'risk_assessments', ['risk_zone_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_severity'), 'risk_assessments', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_assessments_valid_until'), 'risk_assessments', ['valid_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_valid_until'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_severity'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_zone_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_public_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_forecast_horizon_minutes'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessed_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
