"""Create alert deliveries table

Revision ID: 6fb6ffe94207
Revises: 72970b64198f
Create Date: 2026-08-27 19:30:16.156214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb6ffe94207'
down_revision: Union[str, Sequence[str], None] = '72970b64198f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_channel'), 'alert_deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_id'), 'alert_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_public_id'), 'alert_deliveries', ['public_id'], unique=True)
    op.create_index(op.f('ix_alert_deliveries_recipient'), 'alert_deliveries', ['recipient'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_status'), 'alert_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_deliveries_status'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_recipient'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_public_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_channel'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    # ### end Alembic commands ###
