"""Add device api key hash to sensors

Revision ID: 9531735357bb
Revises: 199abb6b0998
Create Date: 2026-08-28 13:40:21.814639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9531735357bb'
down_revision: Union[str, Sequence[str], None] = '199abb6b0998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('device_api_key_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'device_api_key_hash')
    # ### end Alembic commands ###
