"""Create landslide events table

Revision ID: b50c065a2edb
Revises: 60ea98256041
Create Date: 2026-08-25 21:37:33.701401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50c065a2edb'
down_revision: Union[str, Sequence[str], None] = '60ea98256041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landslide_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('risk_zone_id', sa.Integer(), nullable=True),
    sa.Column('event_code', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', 'SEVERE', name='landslide_severity'), nullable=False),
    sa.Column('rainfall_24h_mm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_percent', sa.Float(), nullable=True),
    sa.Column('slope_degrees', sa.Float(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('injuries', sa.Integer(), nullable=True),
    sa.Column('affected_area_sq_km', sa.Float(), nullable=True),
    sa.Column('road_blocked', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landslide_events_district'), 'landslide_events', ['district'], unique=False)
    op.create_index(op.f('ix_landslide_events_event_code'), 'landslide_events', ['event_code'], unique=True)
    op.create_index(op.f('ix_landslide_events_id'), 'landslide_events', ['id'], unique=False)
    op.create_index(op.f('ix_landslide_events_latitude'), 'landslide_events', ['latitude'], unique=False)
    op.create_index(op.f('ix_landslide_events_longitude'), 'landslide_events', ['longitude'], unique=False)
    op.create_index(op.f('ix_landslide_events_occurred_at'), 'landslide_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_landslide_events_public_id'), 'landslide_events', ['public_id'], unique=True)
    op.create_index(op.f('ix_landslide_events_risk_zone_id'), 'landslide_events', ['risk_zone_id'], unique=False)
    op.create_index(op.f('ix_landslide_events_severity'), 'landslide_events', ['severity'], unique=False)
    op.create_index(op.f('ix_landslide_events_state'), 'landslide_events', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landslide_events_state'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_severity'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_risk_zone_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_public_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_occurred_at'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_longitude'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_latitude'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_event_code'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_district'), table_name='landslide_events')
    op.drop_table('landslide_events')
    # ### end Alembic commands ###
