"""Create villages and road segments tables

Revision ID: c13400a1c845
Revises: 5998ec026736
Create Date: 2026-08-27 00:14:31.392574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13400a1c845'
down_revision: Union[str, Sequence[str], None] = '5998ec026736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('road_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('road_type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=False),
    sa.Column('end_longitude', sa.Float(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('risk_zone_id', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blockage_reason', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_segments_district'), 'road_segments', ['district'], unique=False)
    op.create_index(op.f('ix_road_segments_id'), 'road_segments', ['id'], unique=False)
    op.create_index(op.f('ix_road_segments_name'), 'road_segments', ['name'], unique=False)
    op.create_index(op.f('ix_road_segments_public_id'), 'road_segments', ['public_id'], unique=True)
    op.create_index(op.f('ix_road_segments_risk_zone_id'), 'road_segments', ['risk_zone_id'], unique=False)
    op.create_index(op.f('ix_road_segments_road_code'), 'road_segments', ['road_code'], unique=True)
    op.create_index(op.f('ix_road_segments_road_type'), 'road_segments', ['road_type'], unique=False)
    op.create_index(op.f('ix_road_segments_state'), 'road_segments', ['state'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('village_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('risk_zone_id', sa.Integer(), nullable=True),
    sa.Column('has_health_facility', sa.Boolean(), nullable=False),
    sa.Column('has_school', sa.Boolean(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_district'), 'villages', ['district'], unique=False)
    op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
    op.create_index(op.f('ix_villages_latitude'), 'villages', ['latitude'], unique=False)
    op.create_index(op.f('ix_villages_longitude'), 'villages', ['longitude'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_index(op.f('ix_villages_public_id'), 'villages', ['public_id'], unique=True)
    op.create_index(op.f('ix_villages_risk_zone_id'), 'villages', ['risk_zone_id'], unique=False)
    op.create_index(op.f('ix_villages_state'), 'villages', ['state'], unique=False)
    op.create_index(op.f('ix_villages_village_code'), 'villages', ['village_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_villages_village_code'), table_name='villages')
    op.drop_index(op.f('ix_villages_state'), table_name='villages')
    op.drop_index(op.f('ix_villages_risk_zone_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_public_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_longitude'), table_name='villages')
    op.drop_index(op.f('ix_villages_latitude'), table_name='villages')
    op.drop_index(op.f('ix_villages_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_district'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_road_segments_state'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_road_type'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_road_code'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_risk_zone_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_public_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_name'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_district'), table_name='road_segments')
    op.drop_table('road_segments')
    # ### end Alembic commands ###
