"""Create risk zones table

Revision ID: f59c8c780e04
Revises: 7e20924a158f
Create Date: 2026-08-23 20:41:34.014861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59c8c780e04'
down_revision: Union[str, Sequence[str], None] = '7e20924a158f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('slope_degrees', sa.Float(), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('terrain_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grid_resolution_m', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_zones_district'), 'risk_zones', ['district'], unique=False)
    op.create_index(op.f('ix_risk_zones_id'), 'risk_zones', ['id'], unique=False)
    op.create_index(op.f('ix_risk_zones_public_id'), 'risk_zones', ['public_id'], unique=True)
    op.create_index(op.f('ix_risk_zones_state'), 'risk_zones', ['state'], unique=False)
    op.create_index(op.f('ix_risk_zones_zone_code'), 'risk_zones', ['zone_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_zones_zone_code'), table_name='risk_zones')
    op.drop_index(op.f('ix_risk_zones_state'), table_name='risk_zones')
    op.drop_index(op.f('ix_risk_zones_public_id'), table_name='risk_zones')
    op.drop_index(op.f('ix_risk_zones_id'), table_name='risk_zones')
    op.drop_index(op.f('ix_risk_zones_district'), table_name='risk_zones')
    op.drop_table('risk_zones')
    # ### end Alembic commands ###
